--  This installation module was generated from ..\..\Packages/DBMS/Postgres/15/domains.jsql.fxlp for Postgres/15

CREATE DOMAIN encrypted__email_server_password AS character varying(256);
CREATE DOMAIN encrypted__access_token AS text;
CREATE DOMAIN encrypted__oidc_client_id AS character varying(200);
CREATE DOMAIN encrypted__oidc_client_secret AS character varying(200);
CREATE DOMAIN encrypted__oidc_sub AS character varying(200);
CREATE DOMAIN encrypted__email AS character varying(255);
CREATE DOMAIN encrypted__salted_ip AS character varying(256);
CREATE DOMAIN internet_name AS character varying(63) CHECK (VALUE ~* '^[a-z0-9\-]*$');
CREATE DOMAIN url AS character varying(256);
CREATE DOMAIN location AS character varying(256);
CREATE DOMAIN object_name AS character varying(63) CHECK (VALUE ~* '^[a-zA-Z_][a-zA-Z_0-9\$]*$');
CREATE DOMAIN validity_period AS integer CHECK (VALUE between 15 and 9999999);
CREATE DOMAIN short_validity_period AS integer CHECK (VALUE between 15 and 86400);
CREATE DOMAIN person_name AS character varying(64);
CREATE DOMAIN email_dispatch_protocol AS character varying(8);
CREATE DOMAIN internet_port AS integer CHECK (VALUE between 1 and 65536);
CREATE DOMAIN email_server_username AS character varying(255);
CREATE DOMAIN semantic_version AS character varying(11) CHECK (VALUE ~* '^([0-9]|[1-9][0-9]{0,2}).([0-9]|[1-9][0-9]{0,2}).([0-9]|[1-9][0-9]{0,2})$');
CREATE DOMAIN build_time AS bigint;
CREATE DOMAIN safe_path AS character varying(255) CHECK (VALUE ~* '^[a-z$0-9_\-\/]+(\.[a-zA-Z0-9_\-]+)?$');
CREATE DOMAIN email_account_username AS character varying(64) CHECK (VALUE ~* '^[a-zA-Z0-9_\-\.]+$');
CREATE DOMAIN file_name AS character varying(200);
CREATE DOMAIN procedure_name AS character varying(127) CHECK (VALUE ~* '^[a-zA-Z_][a-zA-Z_0-9\.\$]*$');
CREATE DOMAIN scope_name AS character varying(50) CHECK (VALUE ~* '^[A-Za-z0-9_\-.:]+$');
CREATE DOMAIN provider_name AS character varying(63);
CREATE DOMAIN tenant_name AS character varying(63);
CREATE DOMAIN postgres_role AS character varying(63);
CREATE DOMAIN username AS character varying(63);
CREATE DOMAIN api_key AS character varying(255);
CREATE DOMAIN security_event_name AS character varying(64);
CREATE DOMAIN security_event_type AS character varying(1);
CREATE DOMAIN error_code AS numeric CHECK (VALUE between 1001 and 1999);
CREATE DOMAIN error_name AS character varying(45);
CREATE DOMAIN http_response_code AS numeric CHECK (VALUE between 100 and 599);
CREATE DOMAIN pg_base_exception_name AS character varying(20);
CREATE DOMAIN pg_error_class_code AS character varying(2);
CREATE DOMAIN pg_error_class_name AS character varying(50);
CREATE DOMAIN pg_error_class_description AS character varying(200);
CREATE DOMAIN pg_sqlstate AS character varying(5);
CREATE DOMAIN pg_exception_name AS character varying(50);
CREATE DOMAIN procedure_access_level AS character varying(1);
