FROM jaaql/jaaql-middleware-python:latest
LABEL maintainer="jaaql.io"

EXPOSE 80

RUN rm -rf $INSTALL_PATH
COPY . $INSTALL_PATH

RUN rm -rf $INSTALL_PATH/jaaql/config/config.ini
RUN mv $INSTALL_PATH/jaaql/config/config-docker.ini $INSTALL_PATH/jaaql/config/config.ini

RUN mkdir -p $INSTALL_PATH/www
RUN mkdir -p $INSTALL_PATH/log
RUN chown -R "$USER":www-data $INSTALL_PATH/www
RUN mkdir -p /etc/letsencrypt/live

VOLUME /etc/letsencrypt
VOLUME /etc/cron.d
VOLUME $INSTALL_PATH/vault

COPY docker/jaaql.service /lib/systemd/system/jaaql.service

VOLUME /etc/nginx/sites-available/

RUN mv $INSTALL_PATH/docker/jaaql.sql /docker-entrypoint-initdb.d/01-jaaql.sql
RUN dos2unix $INSTALL_PATH/docker/pg_reload.sh
RUN mv $INSTALL_PATH/docker/pg_reload.sh /docker-entrypoint-initdb.d/02-pg_reload.sh
RUN mv $INSTALL_PATH/docker/entrypoint.sh entrypoint.sh
RUN dos2unix entrypoint.sh
RUN dos2unix $INSTALL_PATH/base_reboot.sh

ENTRYPOINT ["sh", "entrypoint.sh"]
