FROM jaaql/jaaql-middleware-python:latest
LABEL maintainer="jaaql.io"

EXPOSE 80

VOLUME /etc/letsencrypt
VOLUME /etc/cron.d
VOLUME $INSTALL_PATH/vault
VOLUME /etc/nginx/sites-available/

RUN rm -rf $INSTALL_PATH
COPY . $INSTALL_PATH
COPY docker/jaaql.service /lib/systemd/system/jaaql.service

RUN rm -rf $INSTALL_PATH/jaaql/config/config.ini && \
    mv $INSTALL_PATH/jaaql/config/config-docker.ini $INSTALL_PATH/jaaql/config/config.ini && \
    mkdir -p $INSTALL_PATH/www && \
    mkdir -p $INSTALL_PATH/log && \
    chown -R "$USER":www-data $INSTALL_PATH/www && \
    mkdir -p /etc/letsencrypt/live && \
    mv $INSTALL_PATH/docker/jaaql.sql /docker-entrypoint-initdb.d/01-jaaql.sql && \
    mv $INSTALL_PATH/docker/entrypoint.sh entrypoint.sh && \
    mv $INSTALL_PATH/docker/pg_reboot.sh pg_reboot.sh && \
    dos2unix entrypoint.sh && \
    dos2unix pg_reboot.sh && \
    dos2unix $INSTALL_PATH/base_reboot.sh

ENTRYPOINT ["sh", "entrypoint.sh"]
